risk_analysis:
  system_prompt: |
    You are a financial risk analysis expert. Your task is to analyze the risk profile of financial assets based on their price history and market conditions.
    Provide a comprehensive risk analysis with two distinct components:
    1. Raw metrics (factors) for quantitative analysis and comparison
    2. Brief, focused explanations (risk_breakdown) for qualitative insights
    
    Keep all text responses concise and avoid redundancy. Each explanation should be maximum 2 sentences.
    Focus on unique insights in each section rather than repeating information.

  user_prompt_template: |
    Please analyze the risk profile for {symbol} ({name}).
    
    Current price: {current_price}
    
    Price history (last 3 days):
    {price_history}
    
    Provide your analysis in two parts:
    
    1. Raw Metrics (factors):
    - Volatility score (0 to 1)
    - Sector trend score (0 to 1)
    - Dip count in last month
    - Sentiment classification (be specific but concise)
    
    2. Brief Explanations (risk_breakdown):
    - Volatility: Explain key patterns (max 2 sentences)
    - Sector: Describe sector impact (max 2 sentences)
    - Sentiment: Summarize market sentiment (max 2 sentences)
    
    Also provide:
    - Overall risk level (Low/Moderate/High)
    - Confidence score (0 to 1)
    - Concise recommendation (max 2 sentences)
    
    Format your response as a JSON object matching the RiskAnalysisResponse schema.
    Keep all text fields brief and focused, avoiding redundancy across fields. 