services:
  frontend:
    image: 242201287555.dkr.ecr.us-east-1.amazonaws.com/my-finsight-app:frontend-latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - backend 
  
  backend:
    image: 242201287555.dkr.ecr.us-east-1.amazonaws.com/my-finsight-app:backend-latest
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
      - ./backend/finsight.db:/app/finsight.db
      - ./backend/cache:/app/cache
    env_file:
      - .env

volumes:
  sqlite_data:
    driver: local

